# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_auto_20180724_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 1, 19, 44, 499473)),
        ),
    ]
